[build]
builder = "nixpacks"

[deploy]
startCommand = "python init_db.py && gunicorn application:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"